spring.application.name=return-api
server.port=8085
spring.datasource.url=jdbc:postgresql://localhost:5433/trinetra
spring.datasource.username=trinetra
spring.datasource.password=trinetra_dev
spring.jpa.hibernate.ddl-auto=none
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=return-group
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.prometheus.enabled=true
