spring.application.name=fraud-orchestrator

spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/trinetra_fraud?stringtype=unspecified
spring.datasource.username=fraud_user
spring.datasource.password=fraud_password
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
fastapi.url=http://localhost:8000
scraper.url=http://localhost:3000

server.port=8080
